#!/usr/bin/env bash
#Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02).
sudo apt-get update
sudo apt-get -y install nginx
echo 'Holberton School' > /var/www/html/index.html
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' \
/etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /var/www/html/404.html
sudo sed -i '/listen 80 default_server/a error_page 404 /404.html;' /etc/nginx/sites-available/default
sudo sed -i '/try_files $uri $uri/a add_header X-Served-By $hostname;' /etc/nginx/sites-available/default
sudo service nginx restart
