#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
sudo apt-get install -y --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt upgrade -y
sudo apt-get install -y haproxy=2.0.\*
sudo echo "frontend LOADBALANCER-01
        bind *:80
        mode http
        option forwardfor
        default_backend WEBSERVERS-01

backend WEBSERVERS-01
        mode http
        balance roundrobin
        server 2757-web-01 34.139.131.104:80 check
        server 2757-web-02 34.139.28.201:80 check
        option forwardfor" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart