#!/usr/bin/env bash
# bash script that display content of file /etc/passwd
f="/etc/passwd"
while read line; do
user=$(echo "$line" | cut -d ":" -f 1)
gid=$(echo "$line" | cut -d ":" -f 4)
home=$(echo "$line" | cut -d ":" -f 6)
command=$(echo "$line" | cut -d ":" -f 7)
uid=$(echo "$line" | cut -d ":" -f 3)
pass=$(echo "$line" | cut -d ":" -f 2)
uidinfo=$(echo "$line" | cut -d ":" -f 5)
echo "The user $user is part of the $gid gang, lives in $home and rides $command. $uid's place is protected by the passcode $pass, more info about the user here: $uidinfo"
done < $f
