#!/usr/bin/env bash
# script that configure ufw to allow specific port and deny others
sudo ufw default deny incoming
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw enable
