#!/usr/bin/env bash
# script that change localhost IP and facebook.com IP
cp /etc/hosts ./aux
sed -i "s/127.0.0.1/127.0.0.2/g" ./aux
echo "8.8.8.8 facebook.com" >> ./aux
cat ./aux > /etc/hosts
rm ./aux
