#!/usr/bin/env bash
# script that change Nginx running user to nginx user and change listening port 80 to 8080
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
